URent/URent/Models/NotificationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace URent.Models
{
    public class NotificationViewModel
    {
        public List<SUPTransaction> Notifications { get; set; }

        public Dictionary<int, string> RenterNames { get; set; }
    }
}

URent/URent/Models/SUPUser.cs
namespace URent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SUPUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPUser()
        {
            SUPItemReviews = new HashSet<SUPItemReview>();
            SUPItems = new HashSet<SUPItem>();
            SUPImages = new HashSet<SUPImage>();
            SUPRequests = new HashSet<SUPRequest>();
            SUPTransactions = new HashSet<SUPTransaction>();
            SUPTransactions1 = new HashSet<SUPTransaction>();
            SUPUserReviews = new HashSet<SUPUserReview>();
            SUPUserReviews1 = new HashSet<SUPUserReview>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Date of birth")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "Street address")]
        public string StreetAddress { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "City")]
        public string CityAddress { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "State")]
        public string StateAddress { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "Zip code")]
        public string ZipCode { get; set; }

        public double Lat { get; set; }

        public double Lng { get; set; }

        public DateTime TimeStamp { get; set; } = DateTime.Now;

        [StringLength(128)]
        public string NetUserId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPItemReview> SUPItemReviews { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPItem> SUPItems { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPImage> SUPImages { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPRequest> SUPRequests { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPTransaction> SUPTransactions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPTransaction> SUPTransactions1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPUserReview> SUPUserReviews { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPUserReview> SUPUserReviews1 { get; set; }
    }
}

URent/URent/Controllers/SUPUsersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using URent.Models;
using URent.Abstract;
using System.IO;

namespace URent.Controllers
{
    public class SUPUsersController : Controller
    {
        private SUPContext db = new SUPContext();


        private ISUPRepository repo;

        public SUPUsersController(ISUPRepository itemsRepository)
        {
            repo = itemsRepository;
        }

        /// <summary>
        /// Retrieves user ID of current user from AspNetUsers table.
        /// </summary>
        /// <returns>User ID of current user from AspNetUsers table.</returns>
        [Authorize]
        private string getIdentityID()
        {
            return User.Identity.GetUserId();
        }

        /// <summary>
        /// Retrieves user ID of current user from SUPUsers table that is associated with user ID from AspNetUsers table.
        /// </summary>
        /// <returns>User ID of current user from SUPUsers table associated with user ID from AspNetUsers table.</returns>
        [Authorize]
        private int getSUPUserID()
        {
            string id = getIdentityID();
            SUPUser supUser = db.SUPUsers.Where(u => u.NetUserId.Equals(id)).FirstOrDefault();
            int supUserid = supUser.Id;
            return supUserid;
        }

        public ActionResult ShowAllUserReviews(int id)
        {
            AllReviewsModel model = new AllReviewsModel();
            model.uId = id;
            model.uName = db.SUPUsers.Where(x => x.Id == id).Select(x => x.FirstName).FirstOrDefault().ToString();
            model.uReviews = db.SUPUserReviews.Where(x => x.UserBeingReviewedID == id).OrderByDescending(x => x.Timestamp).ToList();
            return View(model);
        }

        // GET: SUPUsers
        //public ActionResult Index()
        //{
        //    return View(db.SUPUsers.ToList());
        //}

        // GET: SUPUsers/Details/5
        /// <summary>
        /// Displays user account info of a user.
        /// </summary>
        /// <param name="id">ID of a user account</param>
        /// <returns>User account info of a user.</returns>
        //[Authorize]
        public ActionResult Details(int? id)
        {
            SUPUser sUPUser = db.SUPUsers.Find(id); //Finds user account with that ID.
            if (User.Identity.IsAuthenticated)
            {
                var userId = getSUPUserID();
                sUPUser = db.SUPUsers.Where(x => x.Id == userId).Select(y => y).FirstOrDefault();
                return View(sUPUser);
            }
            if (id == null) //No user ID?
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (sUPUser == null) //Does a user account exist?
            {
                return HttpNotFound();
            }
            return View(sUPUser);
        }

        //// GET: SUPUsers/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: SUPUsers/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,FirstName,LastName,DateOfBirth,StreetAddress,CityAddress,StateAddress,ZipCode,TimeStamp,NetUserId")] SUPUser sUPUser)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.SUPUsers.Add(sUPUser);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(sUPUser);
        //}

        // GET: SUPUsers/Edit/5
        /// <summary>
        /// Displays user account edit page.
        /// </summary>
        /// <param name="id">ID of a user account</param>
        /// <returns>User account edit page</returns>
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPUser sUPUser = db.SUPUsers.Find(id);
            //sUPUser.DateOfBirth = dob;
            //sUPUser.NetUserId = netid;
            if (sUPUser == null)
            {
                return HttpNotFound();
            }
            if(id == getSUPUserID())
            {
                return View(sUPUser);
            }
            else
            {
                return RedirectToAction("Error_EditViewAnotherAccount", "Error");
            }
        }

        // POST: SUPUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edits user account
        /// </summary>
        /// <param name="sUPUser">User account to edit.</param>
        /// <returns>Whether edits to a user account was successful.</returns>
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,DateOfBirth,StreetAddress,CityAddress,StateAddress,ZipCode,TimeStamp,Lat,Lng,NetUserId")] SUPUser sUPUser, int? photoElementID)
        {
            if (ModelState.IsValid) //Are required fields filled out?
            {
                if(photoElementID != null)
                {
                    SUPImage sUPImage = db.SUPImages.Where(x => x.UserID == sUPUser.Id).FirstOrDefault();
                    if (sUPImage != null)
                    {
                        db.SUPImages.Remove(sUPImage);
                    }
                    //Fetch the photo matching passed photoElementID value and link it to this listing.
                    SUPImage p = db.SUPImages.Find(photoElementID);
                    p.UserID = sUPUser.Id;
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else //create a listing without any photos
                {
                    db.Entry(sUPUser).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Details", new { id = sUPUser.Id });
            }

            //If not, send user back to edit page to make corrections.
            return View(sUPUser);
        }

        // GET: SUPUsers/Delete/5
        /// <summary>
        /// Displays user account delete page.
        /// </summary>
        /// <param name="id">ID of a user account</param>
        /// <returns>User account delete page</returns>
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPUser sUPUser = db.SUPUsers.Find(id);
            if (sUPUser == null)
            {
                return HttpNotFound();
            }
            return View(sUPUser);
        }

        // POST: SUPUsers/Delete/5
        /// <summary>
        /// Deletes user account
        /// </summary>
        /// <param name="id">ID of a user account</param>
        /// <returns>Successful deletion of a user account.</returns>
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SUPUser sUPUser = db.SUPUsers.Find(id);
            db.SUPUsers.Remove(sUPUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Notifications view
        /// </summary>
        /// <returns>Notifications view</returns>
        [Authorize]
        public ActionResult Notifications()
        {
            return View(); // return list of transactions that have this owner's id
        }

        /// <summary>
        /// User profile view of a user
        /// </summary>
        /// <param name="id">ID of a user profile to view</param>
        /// <returns>User profile of a user</returns>
        [HttpGet]
        public ActionResult UserProfile(int? id)
        {
            ProfileViewModel profile = new ProfileViewModel();
            profile = ProfileHelper(profile, id);
            if (User.Identity.IsAuthenticated)
            {
                profile.UserDoingReviewID = getSUPUserID();
            }
            profile.sUPUserReviews = db.SUPUserReviews.Where(x => x.UserBeingReviewedID == id).OrderByDescending(x => x.Timestamp).ToList();
            GetUserRatingStats(profile, id);

            //SUPUser sUPUser = db.SUPUsers.Find(id); //Finds user account with that ID.
            if (id == null) //No user ID?
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (profile.UserBeingReviewedID == null) //Does a user account exist?
            {
                return HttpNotFound();
            }
            //returns the user with that SUPUser ID
            ViewBag.ReviewerName = db.SUPUsers.Where(x => x.Id == profile.UserDoingReviewID).Select(y => y.FirstName).ToString();
            SUPImage pid = db.SUPImages.Where(a => a.UserID == id).FirstOrDefault(); //Finds an image associated with the listing.
            if (pid != null) //Display an image if it exists in the table.
            {
                ViewBag.Send = pid.Id;
            }
            return View(profile);
        }

        /// <summary>

URent/URent/Views/SUPUsers/Create.cshtml
@model URent.Models.SUPUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SUPUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NetUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NetUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NetUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

URent/URent/Views/SUPUsers/Delete.cshtml
@model URent.Models.SUPUser

@{
    ViewBag.Title = "Delete account";
}

<h2>Delete account</h2>
<br />

<h3>Are you sure you want to close your account?</h3>
<h6 style="color:red">This action cannot be undone!</h6>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NetUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NetUserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

URent/URent/Views/SUPUsers/Details.cshtml
@model URent.Models.SUPUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_UserPageLayout.cshtml";
}

<h1>@Html.ActionLink(Model.FirstName + " " + Model.LastName, "UserProfile", "SUPUsers", new { id = Model.Id }, null)</h1>

<div>
    <hr />

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <h5>
            @String.Format("{0:MM/dd/yyyy}", Model.DateOfBirth)
        </h5>

        <dt>
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>

        <h5>
            @Html.DisplayFor(model => model.StreetAddress)
        </h5>

        <dt>
            @Html.DisplayNameFor(model => model.CityAddress)
        </dt>

        <h5>
            @Html.DisplayFor(model => model.CityAddress)
        </h5>

        <dt>
            @Html.DisplayNameFor(model => model.StateAddress)
        </dt>

        <h5>
            @Html.DisplayFor(model => model.StateAddress)
        </h5>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <h5>
            @Html.DisplayFor(model => model.ZipCode)
        </h5>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit account info", "Edit", new { id = Model.Id}, new { @class = "btn btn-primary"})
</p>

URent/URent/Views/SUPUsers/ShowAllUserReviews.cshtml
@model URent.Models.AllReviewsModel
@{
    ViewBag.Title = "ShowAllUserReviews";
}

<h2>@Model.uName's Reviews</h2>


<br />
@foreach (var item in Model.uReviews)
{
    @Html.ActionLink(item.SUPUser.FirstName + " " + item.SUPUser.LastName, "UserProfile", "SUPUsers", new { id = item.UserDoingReviewID }, null)
    <div style="display: flex">
        <div class="rateit" data-rateit-value="@item.Rating" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
        <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", item.Timestamp)</p>
    </div>
    <p>@item.Details</p>
}

<br />
@Html.ActionLink("Back to User Profile", "UserProfile", "SUPUsers", new { id = Model.uId }, null)

URent/URent/Views/SUPUsers/UserProfile.cshtml
@model URent.Models.ProfileViewModel

@{
    ViewBag.Title = "User profile";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>@Model.FirstName @Model.LastName</h2>

            <!-- Rating stats for this item -->
            <div style="display: flex">
                <h4 style="color: gold; padding-right: 5px;">@String.Format("{0:0.0}", Model.RatingAverage)</h4>
                <div class="rateit" data-rateit-value="@Model.RatingAverage" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
                <h5 class="text-muted" style="padding-left: 10px">@Model.RatingCount review(s)</h5>
            </div>

            <br />
        </div>

        <div class="col-md-6">
            <div class="image-cropper mx-auto d-block">
                @if (ViewBag.Send != null) //Does a photo for this item exist?
                {
                    //If so, display the photo.
                    <img class="profile-pic" src="/Resources/Photo/@ViewBag.Send" alt="Item photo" />
                }
                else
                {
                    //If not, display a placeholder image instead.
                    <img class="profile-pic" src="~/Content/Img/NullProfile.png" alt="Placeholder image" />
                }
            </div>
        </div>

        <br />
    </div>

    <br />
    <br />


    <h3>User reviews for this user</h3>
    <hr />
    @if (Model.sUPUserReviews.Any())
    {
        int i = 0;
        foreach (var review in Model.sUPUserReviews)
        {
            @Html.ActionLink(review.SUPUser1.FirstName + " " + review.SUPUser1.LastName, "UserProfile", "SUPUsers", new { id = review.UserDoingReviewID }, null)
            <div style="display: flex">
                <div class="rateit" data-rateit-value="@review.Rating" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
                <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", review.Timestamp)</p>
            </div>
            <p>@review.Details</p>

            <br />
            i++;
            if(i == 3)
            {
                break;
            }
        }
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Show all reviews
        </button>
    }
    else
    {
        <h5 style="text-align: center">No reviews yet. Be the first to review this user.</h5>
    }

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">All reviews for this user</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @if (Model.sUPUserReviews.Any())
                    {
                        foreach (var review in Model.sUPUserReviews)
                        {
                            @Html.ActionLink(review.SUPUser1.FirstName + " " + review.SUPUser1.LastName, "UserProfile", "SUPUsers", new { id = review.UserDoingReviewID }, null)
                            <div style="display: flex">
                                <div class="rateit" data-rateit-value="@review.Rating" data-rateit-ispreset="true" data-rateit-readonly="true" style="font-size: 17px;"></div>
                                <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", review.Timestamp)</p>
                            </div>
                            <p>@review.Details</p>

                            <br />
                        }
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <br />
    <br />

    @if (Model.UserBeingReviewedID != Model.UserDoingReviewID && Request.IsAuthenticated)
    {

        <h3>Leave a review for this user</h3>
        <hr />

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <fieldset class="rating">
                @Html.RadioButtonFor(model => model.Ratings, "5", new { id = "star5", name = "rating" })<label for="star5">5 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "4", new { id = "star4", name = "rating" })<label for="star4">4 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "3", new { id = "star3", name = "rating" })<label for="star3">3 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "2", new { id = "star2", name = "rating" })<label for="star2">2 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "1", new { id = "star1", name = "rating" })<label for="star1">1 star</label>
            </fieldset>
            @Html.ValidationMessageFor(model => model.Ratings, "", new { @class = "text-danger" })



            @Html.TextAreaFor(model => model.Details, new { @class = "form-control", @rows = 5, @placeholder = "Review this user..." })
            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })


            @Html.HiddenFor(model => model.UserBeingReviewedID)
            @Html.HiddenFor(model => model.UserDoingReviewID)

            <br />
            <input type="submit" value="Submit Review" class="btn btn-primary" />
        }
    }
</div>

@section Scripts {
    @Styles.Render("~/Content/cssjqueryui")
    @Styles.Render("~/Content/rateit.min.css")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Scripts/jquery.rateit.min.js")
}