URent/URent/Models/SUPItem.cs
namespace URent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SUPItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPItem()
        {
            SUPImages = new HashSet<SUPImage>();
            SUPItemReviews = new HashSet<SUPItemReview>();
            SUPRequests = new HashSet<SUPRequest>();
            SUPTransactions = new HashSet<SUPTransaction>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Item name")]
        public string ItemName { get; set; }

        [Required]
        public string Description { get; set; }

        public DateTime TimeStamp { get; set; } = DateTime.Now;

        [Display(Name = "Item availability")]
        public bool IsAvailable { get; set; }

        [Display(Name = "Daily price ($/day)")]
        public decimal DailyPrice { get; set; }

        public double Lat { get; set; }

        public double Lng { get; set; }

        public int OwnerID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPImage> SUPImages { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPItemReview> SUPItemReviews { get; set; }

        public virtual SUPUser SUPUser { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPRequest> SUPRequests { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPTransaction> SUPTransactions { get; set; }
    }
}

URent/URent/Controllers/SUPItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Device.Location;
using Microsoft.AspNet.Identity;
using URent.Models;
using URent.Abstract;

namespace URent.Controllers
{
    public class SUPItemsController : Controller
    {
        private SUPContext db = new SUPContext();

        private ISUPRepository repo;

        public SUPItemsController(ISUPRepository itemsRepository)
        {
            repo = itemsRepository;
        }

        /// <summary>
        /// Retrieves user ID of current logged in user from AspNetUsers table.
        /// </summary>
        /// <returns>User ID of current logged in user from AspNetUsers table.</returns>
        [Authorize]
        private string getIdentityID()
        {
            return User.Identity.GetUserId();
        }

        /// <summary>
        /// Retrieves user ID of current logged in user from SUPUsers table that is associated with user ID from AspNetUsers table.
        /// </summary>
        /// <returns>User ID of current logged in user from SUPUsers table associated with user ID from AspNetUsers table.</returns>
        [Authorize]
        private int getSUPUserID()
        {
            string id = getIdentityID();
            SUPUser supUser = db.SUPUsers.Where(u => u.NetUserId.Equals(id)).FirstOrDefault();
            int supUserid = supUser.Id;
            return supUserid;
        }

        /// <summary>
        /// Checks if a user is the owner of a listing.
        /// </summary>
        /// <param name="listingId">ID of an item listing</param>
        /// <returns>Whether a user is the owner of a listing.</returns>
        [Authorize]
        private bool checkUser(int? listingId)
        {
            int userId = getSUPUserID(); //Retrieves ID of current user
            int listingOwnerId = db.SUPItems.Find(listingId).OwnerID; //Finds owner of the listing
            if (userId == listingOwnerId) //checks if current user is the owner of the listing
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        /// <summary>
        /// Displays the Error page
        /// </summary>
        /// <returns>View of Error.cshtml</returns>
        [Authorize]
        public ActionResult Error()
        {
            return View();
        }


        // GET: SUPItems
        //public ActionResult Index()
        //{
        //    var sUPItems = db.SUPItems.Include(s => s.SUPUser);
        //    return View(sUPItems.ToList());
        //}

        // GET: SUPItems/Details/5
        /// <summary>
        /// Displays details of an item listing
        /// </summary>
        /// <param name="id">ID of an item listing</param>
        /// <returns>Details of an item listing</returns>
        public ActionResult Details(int? id)
        {
            ItemDetailsViewModel model = new ItemDetailsViewModel();
            if (id == null) //No item listing ID?
            {
                return RedirectToAction("Error404", "Error");
            }
            model.sUPItem = db.SUPItems.Find(id); //Finds the item listing associated with that ID
            List<SUPItemReview> reviews = db.SUPItemReviews.Where(x => x.ItemBeingReviewedID == id).OrderByDescending(x => x.Timestamp).ToList();
            model.sUPItemReviews = reviews;

         
            model = DetailsHelper(model, id);
            GetItemRatingStats(model, id);
            //model.ItemBeingReviewedID = id;
            if(User.Identity.IsAuthenticated)
            {
                model.UserDoingReviewID = getSUPUserID();

            }
            
            if (model.sUPItem == null) //Does the item listing exist?
            {
                return HttpNotFound();
            }
            SUPImage pid = db.SUPImages.Where(a => a.ItemID == id).FirstOrDefault(); //Finds an image associated with the listing.
            if (pid != null) //Display an image if it exists in the table.
            {
                ViewBag.Send = pid.Id;
            }
            return View(model);
        }

        /// <summary>
        /// Gets rating stats of an item
        /// </summary>
        /// <param name="model">Item details model</param>
        /// <param name="id">ID of item listing we want to get rating stats on.</param>
        /// <returns>Rating stats of an item</returns>
        public ItemDetailsViewModel GetItemRatingStats(ItemDetailsViewModel model, int? id)
        {
            int? ratingSum = 0;
            int? ratingCount = 0;
            double ratingAverage = 0;

            var ratings = db.SUPItemReviews.Where(d => d.ItemBeingReviewedID == id).Select(y => y.Rating).ToList();
            if (ratings.Count() > 0)
            {
                ratingSum = ratings.Sum(d => d);
                
                ratingCount = ratings.Count();

                ratingAverage = (double) ratingSum / (double) ratingCount;
                model.RatingAverage = ratingAverage;
                model.RatingCount = ratingCount;

                return model;
            }
            else
            {
                model.RatingAverage = 0;
                model.RatingCount = 0;
                return model;
            }
        }

        /// <summary>
        /// Helps get rating stats of an item
        /// </summary>
        /// <param name="model">Item details model</param>
        /// <param name="id">ID of item listing we want to get rating stats on.</param>
        /// <returns>Rating stats of an item</returns>
        public ItemDetailsViewModel DetailsHelper(ItemDetailsViewModel model, int? id)
        {
            model.ItemBeingReviewedID = id;
            return (model);
        }

        /// <summary>
        /// Adds rating and review to an item
        /// </summary>
        /// <param name="itemReview"></param>
        /// <returns>Details page</returns>
        [Authorize, HttpPost]
        public ActionResult Details([Bind(Include = "Details, Ratings, ItemBeingReviewedID, UserDoingReviewID")]ItemDetailsViewModel itemReview)
        {
            SUPItemReview review = new SUPItemReview { Details = itemReview.Details, Rating = itemReview.Ratings, ItemBeingReviewedID = itemReview.ItemBeingReviewedID, UserDoingReviewID = itemReview.UserDoingReviewID };
            db.SUPItemReviews.Add(review);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = itemReview.ItemBeingReviewedID });
        }


        // GET: SUPItems/Create
        /// <summary>
        /// Displays the item listing Create page.
        /// </summary>
        /// <returns>View of Create.cshtml</returns>
        [Authorize]
        public ActionResult Create()
        {
            //ViewBag.OwnerID = new SelectList(db.SUPUsers, supuser.Id, "FirstName");
            return View();
        }

        // POST: SUPItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Creates an item listing.
        /// </summary>
        /// <param name="sUPItem">The item listing to create</param>
        /// <param name="photoElementID">The photo ID this listing will be associated with</param>
        /// <returns>Whether creation of item listing was successful.</returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ItemName,Description,IsAvailable,DailyPrice")] SUPItem sUPItem, int? photoElementID)
        {
            if (ModelState.IsValid) //Are all required fields filled out and valid?
            {
                sUPItem.OwnerID = getSUPUserID(); //Retrieve ID of current user to bind to item listing.
                sUPItem.Lat = db.SUPUsers.Where(x => x.Id.Equals(sUPItem.OwnerID)).Select(x => x.Lat).FirstOrDefault();
                sUPItem.Lng = db.SUPUsers.Where(x => x.Id.Equals(sUPItem.OwnerID)).Select(x => x.Lng).FirstOrDefault();


                if (photoElementID != null) //is a photo ID value present?
                {
                    //Add the item listing to the database
                    db.SUPItems.Add(sUPItem);
                    db.SaveChanges();

                    //Fetch the photo matching passed photoElementID value and link it to this listing.
                    SUPImage p = db.SUPImages.Find(photoElementID);
                    p.ItemID = sUPItem.Id;
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else //create a listing without any photos
                {
                    sUPItem.OwnerID = getSUPUserID();
                    db.SUPItems.Add(sUPItem);
                    db.SaveChanges();
                }

                return RedirectToAction("GetUserItems");

            }
            //ViewBag.OwnerID = new SelectList(db.SUPUsers, "Id", "FirstName", sUPItem.OwnerID);

            //If not, take the user back to the Create page.
            return View(sUPItem);
        }

        // GET: SUPItems/Edit/5
        /// <summary>
        /// Displays an item listing page.
        /// </summary>
        /// <param name="id">ID of an item listing</param>
        /// <returns>Whether access to the edit page of a listing is permitted.</returns>
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null) //No item listing ID?
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPItem sUPItem = db.SUPItems.Find(id); //Finds the item listing associated with that ID.
            if (sUPItem == null) //Does the item listing exist?
            {

URent/URent/Views/SUPItems/Delete.cshtml
@model URent.Models.SUPItem

@{
    ViewBag.Title = "Delete";
}
@if (Request.IsAuthenticated)
{
    Layout = "~/Views/Shared/_UserPageLayout.cshtml";
}

<h2>Delete listing</h2>

<h3>Are you sure you want to delete this listing?</h3>
<div>
    <h6 style="color:red">This action cannot be undone!</h6>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Item name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Item location
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPUser.CityAddress),
            @Html.DisplayFor(model => model.SUPUser.StateAddress)
        </dd>

        <dt>
            Daily rate
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DailyPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirm delete" class="btn btn-danger" />
            @Html.ActionLink("Cancel", "Edit", new { id = Model.Id }, new { @class = "btn btn-outline-primary"})
        </div>
    }
</div>

URent/URent/Views/SUPItems/Details.cshtml
@model URent.Models.ItemDetailsViewModel

@{
    ViewBag.Title = Html.DisplayFor(model => model.sUPItem.ItemName);
}

@*@if (Request.IsAuthenticated) //Is a logged in user viewing this page?
    {
        //If so, show the user sidebar.
        Layout = "~/Views/Shared/_UserPageLayout.cshtml";
    }*@

<div class="container">

    <!-- Item name -->
    <h2>@Html.DisplayFor(model => model.sUPItem.ItemName)</h2>

    <!-- Rating stats for this item -->
    <div style="display: flex">
        <h4 style="color: gold; padding-right: 5px;">@String.Format("{0:0.0}", Model.RatingAverage)</h4>
        <div class="rateit" data-rateit-value="@Model.RatingAverage" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
        <h5 class="text-muted" style="padding-left: 10px">@Model.RatingCount review(s)</h5>
    </div>

    <br />

    <!-- Item photo -->
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                @if (ViewBag.Send != null) //Does a photo for this item exist?
                {
                    //If so, display the photo.
                    <img class="d-block w-100" src="/Resources/Photo/@ViewBag.Send" alt="Item photo">
                }
                else
                {
                    //If not, display a placeholder image instead.
                    <img class="d-block w-100" src="~/Content/Img/default.png" alt="Placeholder image" />
                }
            </div>
        </div>
    </div>

    <hr />

    <!-- Item details -->
    <div class="row">
        <div class="col-sm-3">
            <dt>Owner name</dt>
            <dd>
                @Html.ActionLink(Model.sUPItem.SUPUser.FirstName + " " + Model.sUPItem.SUPUser.LastName, "UserProfile", "SUPUsers", new { id = Model.sUPItem.SUPUser.Id }, null)
            </dd>
        </div>
        <div class="col-sm-3">
            <dt>Item location</dt>
            <dd>
                @Html.DisplayFor(model => model.sUPItem.SUPUser.CityAddress),
                @Html.DisplayFor(model => model.sUPItem.SUPUser.StateAddress)
            </dd>
        </div>
        <div class="col-sm-3">
            <dt>@Html.DisplayNameFor(model => model.sUPItem.DailyPrice)</dt>
            <dd>
                @String.Format("{0:C}", Model.sUPItem.DailyPrice)/day
            </dd>
        </div>
        <div class="col-sm-3">
            <dt>@Html.DisplayNameFor(model => model.sUPItem.IsAvailable)</dt>
            @if (Model.sUPItem.IsAvailable == true)
            {
                <dd style="color:green">Available</dd>
            }
            else
            {
                <dd style="color:red">Not available</dd>
            }
        </div>
    </div>

    <!-- Item description -->
    <div class="row">
        <div class="col-sm-12">
            <dl>
                <dt>@Html.DisplayNameFor(model => model.sUPItem.Description)</dt>
                <dd>@Html.DisplayFor(model => model.sUPItem.Description)</dd>
            </dl>
        </div>
    </div>

    <br />

    @if (Model.sUPItem.IsAvailable == true) //Is the item available?
    {
        // added Request.IsAuthenticated which takes away button to rent items when you are not logged in
        //did this to fix bug where user could rent own item from not being logged in pressing this button and then loggin in
        if (Model.sUPItem.OwnerID != Model.UserDoingReviewID)
        {
            //If so, then we show a "Rent" button.
            @Html.ActionLink("Rent", "Create", "SUPTransactions", new { itemId = Model.sUPItem.Id, dailyPrice = Model.sUPItem.DailyPrice }, new { @class = "btn btn-primary" })
        }
        else if (Request.IsAuthenticated && Model.sUPItem.OwnerID == Model.UserDoingReviewID)
        {
            //If not, we show a "Request" button.
            @Html.ActionLink("Set Unavailable", "makeUnavailable", "SUPItems", new { itemId = Model.sUPItem.Id }, new { @class = "btn btn-primary" })
        }
    }

    @if (Model.sUPItem.IsAvailable == false)
    {
        if (Request.IsAuthenticated && Model.sUPItem.OwnerID == Model.UserDoingReviewID)
        {
            // set unavailable
            @Html.ActionLink("Set Available", "makeAvailable", "SUPItems", new { itemId = Model.sUPItem.Id }, new { @class = "btn btn-primary" })

        }
    }

    @if (Request.IsAuthenticated && Model.sUPItem.OwnerID == Model.UserDoingReviewID) //Is a logged in user viewing this page?
    {
        //Show an "Edit listing" button.
        @Html.ActionLink("Edit listing", "Edit", new { id = Model.sUPItem.Id }, new { @class = "btn btn-outline-primary" })
    }
    <div type="hidden" id="itemId" data-id="@Model.sUPItem.Id"></div>
    <br>

    @*<label>Dates</label>*@

    @*<p>
            <div id="myDatePicker" class="DateBox datepicker" style="width:100%;height:200px;"></div>
                <input class="form-group form-control col-md-2" type="hidden" id="dateHidden" name="datePicker" placeholder="MM/DD/YYYY" />
            <input type="text" id="d" />
            <div id="z"></div>
        </p>*@

    <br />
    <br />

    <h3>User reviews for this item</h3>
    <hr />

    @if (Model.sUPItemReviews.Any())
    {
        int i = 0;
        foreach (var item in Model.sUPItemReviews)
        {
            @Html.ActionLink(item.SUPUser.FirstName + " " + item.SUPUser.LastName, "UserProfile", "SUPUsers", new { id = item.UserDoingReviewID }, null)
            <div style="display: flex">
                <div class="rateit" data-rateit-value="@item.Rating" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
                <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", item.Timestamp)</p>
            </div>
            <p>@item.Details</p>

            <br />

            i++;
            if (i == 3)
            {
                break;
            }
        }
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Show all reviews
        </button>
    }
    else
    {
        <h5 style="text-align: center">No reviews yet. Be the first to review this item.</h5>
    }


    <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">All reviews for this item</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @if (Model.sUPItemReviews.Any())
                        {
                            foreach (var item in Model.sUPItemReviews)
                            {
                                @Html.ActionLink(item.SUPUser.FirstName + " " + item.SUPUser.LastName, "UserProfile", "SUPUsers", new { id = item.UserDoingReviewID }, null)
                                <div style="display: flex">
                                    <div class="rateit" data-rateit-value="@item.Rating" data-rateit-ispreset="true" data-rateit-readonly="true" style="font-size: 17px;"></div>
                                    <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", item.Timestamp)</p>
                                </div>
                                <p>@item.Details</p>

                                <br />
                            }
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    <br />
    <br />

    @if (Model.sUPItem.OwnerID != Model.UserDoingReviewID && Request.IsAuthenticated)
    {
        <h3>Leave a review for this item</h3>
        <hr />

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <fieldset class="rating">
                @Html.RadioButtonFor(model => model.Ratings, "5", new { id = "star5", name = "rating" })<label for="star5">5 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "4", new { id = "star4", name = "rating" })<label for="star4">4 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "3", new { id = "star3", name = "rating" })<label for="star3">3 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "2", new { id = "star2", name = "rating" })<label for="star2">2 stars</label>
                @Html.RadioButtonFor(model => model.Ratings, "1", new { id = "star1", name = "rating" })<label for="star1">1 star</label>
            </fieldset>

            <br />
            @Html.ValidationMessageFor(model => model.Ratings, "", new { @class = "text-danger" })


            @Html.TextAreaFor(model => model.Details, new { @class = "form-control", @rows = 5, @placeholder = "Review this item..." })
            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.ItemBeingReviewedID)
            @Html.HiddenFor(model => model.UserDoingReviewID)

            <br />

            <input type="submit" value="Submit Review" class="btn btn-primary" />
        }
    }
</div>

@section Scripts {
    @Styles.Render("~/Content/cssjqueryui")
    @Styles.Render("~/Content/rateit.min.css")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @*@Scripts.Render("~/Scripts/Calendar.js")*@
    @Scripts.Render("~/Scripts/jquery.rateit.min.js")
}

URent/URent/Views/SUPItems/GetUserItems.cshtml
@model IEnumerable<URent.Models.SUPItem>

@{
    ViewBag.Title = "My item listings";
    Layout = "~/Views/Shared/_UserPageLayout.cshtml";
}

<h2>My item listings</h2>
<br />

<table class="table">
    <tr>
        <th>
            Item name
        </th>
        <th>
            Daily rate ($/day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ItemName, "Details", "SUPItems", new { id = item.Id }, null)
            </td>
            <td>
                @String.Format("{0:C}", item.DailyPrice)
            </td>
            @if(item.IsAvailable)
            {
                <td style="color:green">Available</td>
            }
            else
            {
                <td style="color:red">Not available</td>
            }
        </tr>
    }
</table>

URent/URent/Views/SUPItems/Index.cshtml
@model IEnumerable<URent.Models.SUPItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SUPUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DailyPrice)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SUPUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeStamp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        <td>
            @Html.DisplayFor(modeItem => item.DailyPrice)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

URent/URent/Views/SUPItems/Search.cshtml
@model List<URent.Models.SUPItem>
@{
    ViewBag.Title = "Search results";
}
<div class="container">

    <form action="/SUPItems/Search" method="get">
        <label for="distanceSelect">Show item listings within</label>
        <div class="input-group">
            <input name="query" id="geoCoordinate" value="@ViewBag.ResultString" hidden />
            <select name="radius" class="form-control col-sm-2" id="distanceSelect">
                <option>--Select a radius--</option>
                <option>5</option>
                <option>10</option>
                <option>25</option>
                <option>50</option>
                <option>100</option>
            </select>
            <div class="input-group-append">
                <div class="input-group-text">mi</div>
                <button class="btn btn-outline-primary search-btn-outline" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>

    <br />
    <br />

    @if (ViewBag.ShowError)
    {
        <p>Your search didn't return any matches.</p>
    }
    else
    {
        <p>Results matching your search: "<b>@ViewBag.ResultString</b>"</p>
    }

    <!-- Displays results in two-column format -->
    @if (!ViewBag.ShowError)
    {
        for (var i = 0; i < Model.Count; i++)
        {
            <div class="row">
                @do
                {
                    <div class="col-md-6">
                        <div class="card mx-auto">
                            <!-- Adds hyperlink to image of a listing -->
                            <a href="@Url.Action("Details", "SUPItems", new { id = Model[i].Id})">
                                <img class="card-img-top" src="/Resources/HomePhoto/@Model[i].Id">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">@Html.ActionLink(Model[i].ItemName, "Details", "SUPItems", new { id = Model[i].Id }, null)</h5>
                                <p class="card-text">@Model[i].SUPUser.CityAddress, @Model[i].SUPUser.StateAddress</p>
                                <p class="card-subtitle"><b>@String.Format("{0:C}", Model[i].DailyPrice)/day</b></p>
                                @if (Model[i].IsAvailable)
                                {
                                    <p class="card-text" style="color:green">Available</p>
                                }
                                else
                                {
                                    <p class="card-text" style="color:red">Not available</p>
                                }
                                <br />
                                @Html.ActionLink("View listing", "Details", "SUPItems", new { id = Model[i].Id }, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>

                    i++; //increment counter by 1 while in do-while loop

                    if (i >= Model.Count) //Have we reached end of list of items listings?
                    {
                        break; //breaks out of the do-while and for loops
                    }
                }
                while (i % 2 != 0);
                @{ i--;}
            </div>
        }
    }
</div>

URent/URent/Views/SUPItems/ShowAllItemReviews.cshtml
@model URent.Models.AllReviewsModel
@{
    ViewBag.Title = "ShowAllItemReviews";
}

<h2>@Model.iName's Reviews</h2>


<br />
@foreach (var item in Model.iReviews)
{
    @Html.ActionLink(item.SUPUser.FirstName + " " + item.SUPUser.LastName, "UserProfile", "SUPUsers", new { id = item.UserDoingReviewID }, null)
    <div style="display: flex">
        <div class="rateit" data-rateit-value="@item.Rating" data-rateit-ispreset="true" data-rateit-mode="font" data-rateit-readonly="true" style="font-size: 25px;"></div>
        <p class="text-muted" style="padding-left: 10px">@String.Format("{0:MM/dd/yyyy}", item.Timestamp)</p>
    </div>
    <p>@item.Details</p>
}

<br />
@Html.ActionLink("Back to Item Details", "Details", "SUPItems", new { id = Model.iId }, null)