Documents/DiscussionProject/DiscussionProject/Models/SUPComment.cs
namespace DiscussionProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SUPComment
    {
        public int ID { get; set; }

        [Required, DisplayName("Comment title")]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        public string Details { get; set; }

        [DisplayName("Created on")]
        public DateTime TIMESTAMP { get; set; } = DateTime.Now;

        [DisplayName("User")]
        public int UserID { get; set; }

        [DisplayName("Discussion thread")]
        public int DiscussionID { get; set; }

        public virtual SUPDiscussion SUPDiscussion { get; set; }

        public virtual SUPUser SUPUser { get; set; }
    }
}

Documents/DiscussionProject/DiscussionProject/Controllers/SUPCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiscussionProject.Models;

namespace DiscussionProject.Controllers
{
    public class SUPCommentsController : Controller
    {
        private SUPContext db = new SUPContext();

        // GET: SUPComments
        public ActionResult Index()
        {
            var sUPComments = db.SUPComments.Include(s => s.SUPDiscussion).Include(s => s.SUPUser);
            return View(sUPComments.ToList());
        }

        // GET: SUPComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPComment sUPComment = db.SUPComments.Find(id);
            if (sUPComment == null)
            {
                return HttpNotFound();
            }
            return View(sUPComment);
        }

        // GET: SUPComments/Create
        public ActionResult Create()
        {
            ViewBag.DiscussionID = new SelectList(db.SUPDiscussions, "ID", "Title");
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName");
            return View();
        }

        // POST: SUPComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Details,UserID,DiscussionID")] SUPComment sUPComment)
        {
            if (ModelState.IsValid)
            {
                db.SUPComments.Add(sUPComment);
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }

            ViewBag.DiscussionID = new SelectList(db.SUPDiscussions, "ID", "Title", sUPComment.DiscussionID);
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPComment.UserID);
            return View(sUPComment);
        }

        // GET: SUPComments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPComment sUPComment = db.SUPComments.Find(id);
            if (sUPComment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DiscussionID = new SelectList(db.SUPDiscussions, "ID", "Title", sUPComment.DiscussionID);
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPComment.UserID);
            return View(sUPComment);
        }

        // POST: SUPComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Details,UserID,DiscussionID")] SUPComment sUPComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sUPComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }
            ViewBag.DiscussionID = new SelectList(db.SUPDiscussions, "ID", "Title", sUPComment.DiscussionID);
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPComment.UserID);
            return View(sUPComment);
        }

        // GET: SUPComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPComment sUPComment = db.SUPComments.Find(id);
            if (sUPComment == null)
            {
                return HttpNotFound();
            }
            return View(sUPComment);
        }

        // POST: SUPComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SUPComment sUPComment = db.SUPComments.Find(id);
            db.SUPComments.Remove(sUPComment);
            db.SaveChanges();
            return RedirectToAction("Index", "Home", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/DiscussionProject/DiscussionProject/Controllers/SUPDiscussionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiscussionProject.Models;

namespace DiscussionProject.Controllers
{
    public class SUPDiscussionsController : Controller
    {
        private SUPContext db = new SUPContext();

        // GET: SUPDiscussions
        public ActionResult Index()
        {
            var sUPDiscussions = db.SUPDiscussions.Include(s => s.SUPUser);
            return View(sUPDiscussions.ToList());
        }

        // GET: SUPDiscussions/Details/5
        public ActionResult Details(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            
            //if (sUPDiscussion == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(sUPDiscussion);
            var model = new SUPDiscussionDetails();
            model.sUPDiscussion = db.SUPDiscussions.Find(id);
            //model.sUPComments = db.SUPDiscussions
            //                    .Include(x => x.SUPComments)
            //                    .Where(d => d.DiscussionID.Equals(id))
            //                    .ToList();
            model.sUPComments = db.SUPDiscussions.SelectMany(x => x.SUPComments).Where(y => y.DiscussionID == id).ToList();               
            //model.sUPComments = db.SUPComments.Include(s => s.SUPDiscussion).Where(x => x.DiscussionID.Equals(id)).Include(s => s.SUPUser).ToList();
            //.Include(s => s.SUPDiscussion).Include(s => s.SUPUser)
            return View(model);
        }

        // GET: SUPDiscussions/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName");
            return View();
        }

        // POST: SUPDiscussions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Description,URL,UserID")] SUPDiscussion sUPDiscussion)
        {
            if (ModelState.IsValid)
            {
                db.SUPDiscussions.Add(sUPDiscussion);
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }

            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPDiscussion.UserID);
            return View(sUPDiscussion);
        }

        // GET: SUPDiscussions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPDiscussion sUPDiscussion = db.SUPDiscussions.Find(id);
            if (sUPDiscussion == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPDiscussion.UserID);
            return View(sUPDiscussion);
        }

        // POST: SUPDiscussions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Description,URL,UserID")] SUPDiscussion sUPDiscussion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sUPDiscussion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home", null);
            }
            ViewBag.UserID = new SelectList(db.SUPUsers, "ID", "FirstName", sUPDiscussion.UserID);
            return View(sUPDiscussion);
        }

        // GET: SUPDiscussions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SUPDiscussion sUPDiscussion = db.SUPDiscussions.Find(id);
            if (sUPDiscussion == null)
            {
                return HttpNotFound();
            }
            return View(sUPDiscussion);
        }

        // POST: SUPDiscussions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SUPDiscussion sUPDiscussion = db.SUPDiscussions.Find(id);
            db.SUPDiscussions.Remove(sUPDiscussion);
            db.SaveChanges();
            return RedirectToAction("Index", "Home", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/DiscussionProject/DiscussionProject/Views/SUPComments/Create.cshtml
@model DiscussionProject.Models.SUPComment

@{
    ViewBag.Title = "Add a comment";
}

<h2>Add a comment</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscussionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DiscussionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DiscussionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add comment" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/DiscussionProject/DiscussionProject/Views/SUPComments/Delete.cshtml
@model DiscussionProject.Models.SUPComment

@{
    ViewBag.Title = "Delete comment";
}

<h2>Delete comment</h2>

<h3>Are you sure you want to delete this?</h3>
<h6 style="color:red;">This action cannot be undone!</h6>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Replying to discussion topic
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPDiscussion.Title)
        </dd>

        <dt>
            User
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIMESTAMP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIMESTAMP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-secondary" })
    </div>
    }
</div>

Documents/DiscussionProject/DiscussionProject/Views/SUPComments/Details.cshtml
@model DiscussionProject.Models.SUPComment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SUPComment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SUPDiscussion.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPDiscussion.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SUPUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SUPUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIMESTAMP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIMESTAMP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Documents/DiscussionProject/DiscussionProject/Views/SUPComments/Edit.cshtml
@model DiscussionProject.Models.SUPComment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit comment</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, "Comment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscussionID, "Replying to discussion topic", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DiscussionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DiscussionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Details", "SUPDiscussions", new { id = Model.ID }, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/DiscussionProject/DiscussionProject/Views/SUPComments/Index.cshtml
@model IEnumerable<DiscussionProject.Models.SUPComment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SUPDiscussion.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SUPUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Details)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIMESTAMP)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SUPDiscussion.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SUPUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Details)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TIMESTAMP)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>